---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: { }
---
# change default in dnsNames to namespace that you deployed the webhook in
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhook-server-cert
spec:
  dnsNames:
    - webhook-server
    - webhook-server.${NAMESPACE}
    - webhook-server.${NAMESPACE}.svc
    - webhook-server.${NAMESPACE}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: webhook-server-cert
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: webhook-server
  annotations:
    cert-manager.io/inject-ca-from: ${NAMESPACE}/webhook-server-cert
webhooks:
  - name: "validate.webhook.com"
    rules:
      - apiGroups:   [""]
        apiVersions: ["v1"]
        operations:  ["CREATE", "UPDATE"]
        resources:   ["pods"]
        scope:       "Namespaced"
    clientConfig:
      service:
        namespace: ${NAMESPACE}
        name: webhook-server
        port: 8443
        path: "/validate"
      caBundle:
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Ignore
    timeoutSeconds: 5