---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook-server
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-server
spec:
  type: ClusterIP
  ports:
    - port: 8443
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: webhook-server
    app.kubernetes.io/instance: webhook-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: webhook-server
      app.kubernetes.io/instance: webhook-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webhook-server
        app.kubernetes.io/instance: webhook-server
    spec:
      serviceAccountName: webhook-server
      containers:
        - name: webhook-server
          image: ${IMAGE}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8443
              protocol: TCP
          args:
            - -cert-dir=/etc/webhook/certs
            - -port=8443
            - -debug=true
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: webhook-server-cert